version: '2'
services:
  web:
    container_name: functions_app_dev
    build: .
    ports:
      - "127.0.0.1:8100:8100"
    networks:
      - functions_net_dev
    environment:
      REDIS_ENDPOINT: redis://redis:6379/0
    depends_on:
      - redis
  redis:
    container_name: functions_db_dev
    image: redis
    volumes:
      - functions_vol_dev:/data
    networks:
      - functions_net_dev

volumes:
  functions_vol_dev:

networks:
  functions_net_dev:
